version: '2'
services:
    ewidencja-app:
        image: ewidencja
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ewidencja-mysql:3306/ewidencja?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ewidencja-mysql:
        extends:
            file: mysql.yml
            service: ewidencja-mysql
